### ISSUE TITLE
Less Manual Install Steps

### ISSUE THREAD

**Issue by jneilliii** [ArduCAM/ArducamCameraControl#1]
If you update the line [here](https://github.com/ArduCAM/ArducamCameraControl/blob/14c26e10c6d7ba6b66190578f522a63832bef98c/setup.py#L36) to be `plugin_requires = ["smbus"]` then OctoPrint will automatically install smbus for you.

**Comment by ArduCAM** [comment]
Ok.Thanks for reminding.
The new release has added.

**Comment by jneilliii** [comment]
Thanks, merging the plugin into the repo now...thanks for this plugin BTW, I can finally focus my camera as expected.
